unstable_features = true
brace_style = "AlwaysNextLine"
combine_control_expr = false
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
edition = "2021"
format_code_in_doc_comments = true
hard_tabs = false
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_block_trailing_comma = true
max_width = 100
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
space_after_colon = true
space_before_colon = true
spaces_around_ranges = true
struct_field_align_threshold = 9
trailing_comma = "Vertical"
use_try_shorthand = true
version = "Two"
wrap_comments = true
